spring.application.name=MainP_Back
server.port=8081
# MySQL JDBC settings
spring.datasource.url=jdbc:mysql://localhost:3306/mainp_back
spring.datasource.username=root
spring.datasource.password=yts8007
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update 
spring.jpa.open-in-view=false



#access key
cloud.aws.credentials.accessKey=AKIAXAJL2R7YFKAZQV6V
#secret key
cloud.aws.credentials.secretKey=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
#
cloud.aws.s3.bucketName=yts-bucket
#
cloud.aws.region.static=ap-southeast-2
#cloud formation
cloud.aws.stack.auto=false